package enums;

public enum LogActions {
	SIGNUP, LOGIN, LOGOUT, OPEN, CLOSE, 
	TIMELINE_READ, TIMELINE_SYNC,
	CONTEXT_READ, CONTEXT_INIT, CONTEXT_REFRESH,CONTEXT_DELETE, 
	VIEWS, DETAILVIEWS,
	PUBLIC_MEMENTO_NEW, PUBLIC_MEMENTO_MODIFY, PUBLIC_MEMENTO_DELETE, PUBLIC_MEMENTO_READ,
	QUESTION_READ, QUESTION_ANSWER,
	STORY_NEW, STORY_MODIFY, STORY_DELETE, STORY_READ,
	MEMENTO_NEW, MEMENTO_MODIFY, MEMENTO_DELETE, MEMENTO_READ, 	
	FILE_NEW, 
	STORY_SHARE, STORY_COMMENT,
	RELATIONSHIP_NEW;
}
